# Generated by Django 4.2.7 on 2025-12-03 03:50

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary_date", models.DateField(default=datetime.date.today)),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_claims", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="claims.practice",
                    ),
                ),
            ],
            options={
                "unique_together": {("practice", "summary_date")},
            },
        ),
    ]
