# Generated by Django 4.2.7 on 2025-12-03 03:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("member_id", models.CharField(blank=True, max_length=50)),
                ("payer_id", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("npi", models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ("tax_id", models.CharField(blank=True, max_length=20)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("npi", models.CharField(blank=True, max_length=10)),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("license_state", models.CharField(blank=True, max_length=2)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapists",
                        to="claims.practice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField()),
                ("cpt_code", models.CharField(max_length=10)),
                ("icd10_code", models.CharField(max_length=10)),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "copay_collected",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("payer_id", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="claims.patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="claims.practice",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="claims.therapist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="claims.practice",
            ),
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_number", models.CharField(max_length=50, unique=True)),
                ("payer_id", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready for Submission"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                            ("denied", "Denied"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("charge_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "copay_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "allowed_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "paid_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                ("denial_reason", models.CharField(blank=True, max_length=500)),
                ("edi_payload", models.JSONField(blank=True, null=True)),
                ("validation_errors", models.JSONField(default=list)),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="claims.practice",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="claims.session",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="therapist",
            index=models.Index(fields=["practice"], name="claims_ther_practic_ff3d16_idx"),
        ),
        migrations.AddConstraint(
            model_name="therapist",
            constraint=models.UniqueConstraint(
                fields=("practice", "npi"), name="unique_therapist_npi_per_practice"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["practice"], name="claims_sess_practic_da948b_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["practice", "session_date"], name="claims_sess_practic_7ed59b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["patient"], name="claims_sess_patient_d00de0_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["therapist"], name="claims_sess_therapi_400650_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["practice"], name="claims_pati_practic_8fbfdb_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["practice", "date_of_birth"], name="claims_pati_practic_a0d4cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["practice"], name="claims_clai_practic_2fd3f9_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["status"], name="claims_clai_status_b4f911_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["practice", "status"], name="claims_clai_practic_8f5458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["session"], name="claims_clai_session_9c35f5_idx"),
        ),
    ]
