# Generated by Django 4.2.7 on 2025-12-03 03:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payer_name", models.CharField(max_length=100)),
                ("member_id", models.CharField(max_length=50)),
                ("group_number", models.CharField(blank=True, max_length=50)),
                ("copay_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_coverage",
                        to="claims.patient",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_coverages",
                        to="claims.practice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
